# Generated by Django 5.2.6 on 2025-10-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='imege',
            new_name='image',
        ),
    ]
